package types

import User
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import types.games.Game
import types.passport.PassportData
import types.payment.Invoice
import types.payment.RefundedPayment
import types.payment.SuccessfulPayment
import types.stickers.Sticker

@Serializable
@SerialName("Message")
data class Message(
    val message_id: Long,
    val message_thread_id: Int? = null,
    val from: User? = null,
    val sender_chat: Chat? = null,
    val sender_boost_count: Int? = null,
    val sender_business_bot: User? = null,
    val date: Int,
    val business_connection_id: String? = null,
    val chat: Chat,
    val forward_origin: MessageOrigin? = null,
    val is_topic_message: Boolean? = null,
    val is_automatic_forward: Boolean? = null,
    val reply_to_message: Message? = null,
    val external_reply: ExternalReplyInfo? = null,
    val quote: TextQuote? = null,
    val reply_to_story: Story? = null,
    val via_bot: User? = null,
    val edit_date: Int? = null,
    val has_protected_content: Boolean? = null,
    val is_from_offline: Boolean? = null,
    val media_group_id: String? = null,
    val author_signature: String? = null,
    val text: String? = null,
    val entities: List<MessageEntity>? = null,
    val link_preview_options: LinkPreviewOptions? = null,
    val effect_id: String? = null,
    val animation: Animation? = null,
    val audio: Audio? = null,
    val document: Document? = null,
    val paid_media: PaidMediaInfo? = null,
    val photo: List<PhotoSize>? = null,
    val sticker: Sticker? = null,
    val story: Story? = null,
    val video: Video? = null,
    val video_note: VideoNote? = null,
    val voice: Voice? = null,
    val caption: String? = null,
    val caption_entities: List<MessageEntity>? = null,
    val show_caption_above_media: Boolean? = null,
    val has_media_spoiler: Boolean? = null,
    val contact: Contact? = null,
    val dice: Dice? = null,
    val game: Game? = null,
    val poll: Poll? = null,
    val venue: Venue? = null,
    val location: Location? = null,
    val new_chat_members: List<User>? = null,
    val left_chat_member: User? = null,
    val new_chat_title: String? = null,
    val new_chat_photo: List<PhotoSize>? = null,
    val delete_chat_photo: Boolean? = null,
    val group_chat_created: Boolean? = null,
    val supergroup_chat_created: Boolean? = null,
    val channel_chat_created: Boolean? = null,
    val message_auto_delete_timer_changed: MessageAutoDeleteTimerChanged? = null,
    val migrate_to_chat_id: Long? = null,
    val migrate_from_chat_id: Long? = null,
    val pinned_message: MaybeInaccessibleMessage? = null,
    val invoice: Invoice? = null,
    val successful_payment: SuccessfulPayment? = null,
    val refunded_payment: RefundedPayment? = null,
    val users_shared: UsersShared? = null,
    val chat_shared: ChatShared? = null,
    val connected_website: String? = null,
    val write_access_allowed: WriteAccessAllowed? = null,
    val passport_data: PassportData? = null,
    val proximity_alert_triggered: ProximityAlertTriggered? = null,
    val boost_added: ChatBoostAdded? = null,
    val chat_background_set: ChatBackground? = null,
    val forum_topic_created: ForumTopicCreated? = null,
    val forum_topic_edited: ForumTopicEdited? = null,
    val forum_topic_closed: ForumTopicClosed? = null,
    val forum_topic_reopened: ForumTopicReopened? = null,
    val general_forum_topic_hidden: GeneralForumTopicHidden? = null,
    val general_forum_topic_unhidden: GeneralForumTopicUnhidden? = null,
    val giveaway_created: GiveawayCreated? = null,
    val giveaway: Giveaway? = null,
    val giveaway_winners: GiveawayWinners? = null,
    val giveaway_completed: GiveawayCompleted? = null,
    val video_chat_scheduled: VideoChatScheduled? = null,
    val video_chat_started: VideoChatStarted? = null,
    val video_chat_ended: VideoChatEnded? = null,
    val video_chat_participants_invited: VideoChatParticipantsInvited? = null,
    val web_app_data: WebAppData? = null,
    val reply_markup: InlineKeyboardMarkup? = null
) : MaybeInaccessibleMessage()
